version: '3'

services:
  php:
    build:
      context: docker/php
    environment:
      HISTFILE: /root/history/.history
      ENV: /root/.bashrc
    volumes:
      - .:/var/www/html:cached
      - php_socket:/var/run/php
      - php_history:/root/history

  nginx:
    image: nginx:1.24-alpine3.17
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/var/www/html/public:ro
      - php_socket:/var/run/php
    ports:
      - '8080:80'

volumes:
  php_history: ~
  php_socket: ~
